### ISSUE TITLE
Change API reference to released version

### ISSUE THREAD

**Issue by CharliePoole** [nunit/teamcity-event-listener#23]
The nuget reference to NUnit.Engine.API refers to a dev release on myget because there is as yet no production release of the API. Once the 3.5 engine is released, this should be changed for each extension.

**Comment by NikolayPianikov** [comment]
@CharliePoole  I've checked that the extension works fine with any versions of nunit >= 3.4.1 and it does not depend on the referenced version of `nunit.engine.api.dll`. Do you think I should do it and publish new package teamcity-event-listener.dll 1.0.3 after NUnit.Engine.API will be released?

**Comment by CharliePoole** [comment]
It's up to you in this case. For the other extensions, I plan to make the change because it would completely eliminate the use of the myget feed. I don't think that's true for your script.

Also, even though I'm making the change, I don't plan to do any hot-fix releases because it's only a development dependency.
