### ISSUE TITLE
[Teamcity] Broken characters encoding in tests result output.

### ISSUE THREAD

**Issue by rprouse** [nunit/teamcity-event-listener#36]
@cezarypiatek commented on [Wed Feb 08 2017](https://github.com/nunit/nunit-console/issues/176)

After migrating our tests from NUnit 2.5.3 to NUnit 3.6 Teamcity starts to display test results with invalid characters set. Sometimes we are using polish characters in test names and until now everything was displayed correctly. For example

previously:
```plaintext
LeaseProductAdditionalRepositoryTest.da_się_przefiltrować_produkty_dodatkowe_po_nazwie 
```
now:
```plaintext
LeaseProductAdditionalRepositoryTest.da_si©_przefiltrowa†_produkty_dodatkowe_po_nazwie 
```

We are using TeamCity 9.1.1 and Nunit3-Console (v3.6)
How to setup correct chars encoding (UTF-8) ?

---

@s-tarasov commented on [Thu Feb 09 2017](https://github.com/nunit/nunit-console/issues/176#issuecomment-278738906)

Same problem with cyrillic symbols

```
[Functional.Tests.Web.TestRegistrationFromMain] [Test Output]
���� ॣ����樨 � ����� ������� ��࠭���
��稭��� ॣ������ ���짮��⥫�: TempToDeleteAutoCreation9557493@example.ru � ��஫��: 1234567890
��������� �����襭�
������ ���� ஦����� �� ��뫢��饬 ����
���� ���� ஦����� �����襭
���室�� �� ��࠭��� � १ � �஢��塞 ���� �� ��⨢���

```
We are using TeamCity 10.0.1 and Nunit3-Console (v3.6)

---

@rprouse commented on [Thu Feb 09 2017](https://github.com/nunit/nunit-console/issues/176#issuecomment-278741629)

I expect that this may be an issue with the TeamCity event listener that JetBrains wrote for NUnit 3. @NikolayPianikov can you confirm so that we can move this issue to your repo?

---

@NikolayPianikov commented on [Thu Feb 09 2017](https://github.com/nunit/nunit-console/issues/176#issuecomment-278780190)

@rprouse yes, please move

**Comment by NikolayPianikov** [comment]
The nunit console uses Encoding.Default codepage to write a text to stdOut by default and TeamCity gets this text from stdOut. Encoding.Default depends on your "Regional Settings" (for programms that do not support Unicode). The Unicode related text might be corrupted if the nunit console or other applications try writing using the OS code page. So you have several options:
1. Change this settings for the computer which is used for running tests.
2. Use the additional nunit command line argument to specify the encoding: for example `--encoding=utf-8` helps for many cases.
3. Create a request to add `Console.OutputEncoding = Encoding.UTF8` to the first lines of this [method NUnit.ConsoleRunner.Program.Main](https://github.com/nunit/nunit-console/blob/master/src/NUnitConsole/nunit3-console/Program.cs) to use UTF8 as default code page. @rprouse, @CharliePoole what do you think about option 3?

**Comment by cezarypiatek** [comment]
@NikolayPianikov I've tried solution 2 and 3 and it has no effect. Additionally when I add Console.OutputEncoding = Encoding.UTF8 to my UT it fails when I run tests in Visual Studio with Resharper Test Runner (it throws null reference exception)

**Comment by NikolayPianikov** [comment]
@cezarypiatek oh, I forgot to note, TeamCity should use the same encoding. So try adding the configuration parameter "teamcity.runner.commandline.stdstreams.encoding=UTF-8" to your TeamCity project/configuration to specify encoding

**Comment by cezarypiatek** [comment]
@NikolayPianikov adding configuration parameter in TeamCity solved the problem. So thank you for your help.
 It would be very helpful if  somebody could add --encoding=utf-8 parameter to NUnit Console documentation https://github.com/nunit/docs/wiki/Console-Command-Line (This parameter is missing in the options list)

**Comment by CharliePoole** [comment]
@cezarypiatek I updated the docs. Thanks for calling it to our attention.

**Comment by s-tarasov** [comment]
Thanks!
