### ISSUE TITLE
TeamCity does not parse service messages inside errors/output of tests

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/teamcity-event-listener#4]
TeamCity now parses service messages inside other service messages, but only if original message was tagged with tc:parseServiceMessagesInside. Example:
## teamcity[testStdOut name='test1' out='##teamcity|[buildStatisticValue key=|'my_stat_value|' value=|'125|'|]' tc:tags='tc:parseServiceMessagesInside']

Such parsing is supported for the following types of service messages: message, testStdOut, testStdErr.

**Comment by CharliePoole** [comment]
It's preferable to move issues between repos using zenhub, so that all the discussion is copied. I created #6 to replace this one.
