### ISSUE TITLE
Add Nikolay to the Copyright

### ISSUE THREAD

**Issue by CharliePoole** [nunit/teamcity-event-listener#40]
@NikolayPianikov 
I originally wrote the code that was part of the engine for issuing TC messages. Then I extracted it and created the first version of the extension. As a result the copyright is in my name.

You have done most of the work for quite a while and that's what we expect to see in the future. I'd like to revise the copyright to list both of us. Would that be OK with you?

I don't know what your arrangement about this is with your company. I suppose you might have to check to ensure it's OK for your name to go on this personally. I'll leave that up to you. Between just us two, it's as simple as agreeing and changing the notices. If the company is involved, it will probably take more.

If you OK this, I'll give you a PR.

**Comment by NikolayPianikov** [comment]
@CharliePoole it is ok for me, but I will discuss it with team, give me PR please

**Comment by NikolayPianikov** [comment]
@CharliePoole I've discussed this question with colleague whos are responsible for similar questions, so it is preferable for us to use JetBrains in copyrights, because it's fair, if it is possible. If it is not, it will be ok for me if you will be one person mentioned in these copyrights.

**Comment by CharliePoole** [comment]
@NikolayPianikov Too bad. I had hoped to share it with you.

I guess that means your work is "for hire" (US term) by Jetbrains. I personally know that you are allowed to make this contribution to NUnit because of a meeting we had, but at some time, the project may want to get a contribution agreement signed - we don't yet have one.

I'm not willing to share the copyright with a for-profit company at this point. In future, if Jetbrains takes this over entirely, we may have to talk to some of your colleagues on the business side of things.
