### ISSUE TITLE
Support testStdErr

### ISSUE THREAD

**Issue by flcdrg** [nunit/teamcity-event-listener#47]
It might be useful to support TeamCity's `testStdErr` service message for errors.

**Comment by NikolayPianikov** [comment]
@flcdrg unfortunately it is not possible for the current version of NUnit, but as workaround you could use [this approach](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter). I've created [this issue](https://github.com/nunit/nunit-console/issues/305)

**Comment by ChrisMaddock** [comment]
The relevant change will now be in NUnit 3.9, thanks to @MhdTlb! 😄
