### ISSUE TITLE
Colon's in testcase data are replaced with <space> in the Teamcity service messages

### ISSUE THREAD

**Issue by chrisgeorge0911** [nunit/teamcity-event-listener#68]
Nunit 3.11 / Nunit console 3.10

Having a simple parameterised testcase such as

```
[TestCase("test1", ":")]
[TestCase("test2", "-")]
public void TestMethod1(string name, string data)
{
    Assert.IsTrue(true);
}
```

Runs fine, but with --teamcity, the resulting teamcity service messages look like:

```
##teamcity[flowStarted flowId='PID_31160_0-1004' parent='PID_31160']
##teamcity[testSuiteStarted name='UnitTestProject1.dll' flowId='PID_31160_0-1004']
##teamcity[flowStarted flowId='PID_31160_0-1001' parent='PID_31160_0-1004']
##teamcity[testStarted name='UnitTestProject1.UnitTest1.TestMethod1("test1"," ")' captureStandardOutput='false' flowId='PID_31160_0-1001']
##teamcity[testFinished name='UnitTestProject1.UnitTest1.TestMethod1("test1"," ")' duration='13' flowId='PID_31160_0-1001']
##teamcity[flowFinished flowId='PID_31160_0-1001']
##teamcity[flowStarted flowId='PID_31160_0-1002' parent='PID_31160_0-1004']
##teamcity[testStarted name='UnitTestProject1.UnitTest1.TestMethod1("test2","-")' captureStandardOutput='false' flowId='PID_31160_0-1002']
##teamcity[testFinished name='UnitTestProject1.UnitTest1.TestMethod1("test2","-")' duration='0' flowId='PID_31160_0-1002']
##teamcity[flowFinished flowId='PID_31160_0-1002']
##teamcity[testSuiteFinished name='UnitTestProject1.dll' flowId='PID_31160_0-1004']
##teamcity[flowFinished flowId='PID_31160_0-1004']
```

Notice the lack of colon's in the test1 lines.

This becomes a problem when there are other parameterised tests that actually pass a space, because teamcity underreports the number of issues as they are not unique.

**Comment by NikolayPianikov** [comment]
@chrisgeorge0911 unfortunately I have to replace the colon symbol because of TeamCity treats it as a delimiter of an assembly name and a test class/method name. As alternative I could replace it by '%3A' for instance. But in your test report you will see the line like `Tests.Test1("test1","%3A")`. Or I could add a parameter to specify a replacement string.

**Comment by chrisgeorge0911** [comment]
> @chrisgeorge0911 unfortunately I have to replace the colon symbol because of TeamCity treats it as a delimiter of an assembly name and a test class/method name. As alternative I could replace it by '%3A' for instance. But in your test report you will see the line like `Tests.Test1("test1","%3A")`. Or I could add a parameter to specify a replacement string.

@NikolayPianikov  how about replacing ":" with "\<colon\>"?  My worry with "%3A" is that its more likely to be used as a parameter along with specifying the actual ":" character.  "\<colon\>" is very unlikely to be used as a parameter, but would still uniquely identify that particular test case.

**Comment by NikolayPianikov** [comment]
@chrisgeorge0911 Ok, I will add the environment variable to specify the value for this replacement and by default it will be "<colon>". Thank you

**Comment by chrisgeorge0911** [comment]
Sounds great 👍  thanks

**Comment by NikolayPianikov** [comment]
Fix will be available in NUnit.Extension.TeamCityEventListener 1.0.7

**Comment by abelbraaksma** [comment]
For reference, as this isn't currently anywhere on the net, the environment variable you can use to override the default `<colon>` is `TEAMCITY_COLON_REPLACEMENT`.
