### ISSUE TITLE
Add integration tests and setup CI

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/teamcity-event-listener#8]

**Comment by NikolayPianikov** [comment]
@CharliePoole where can I take the last nuget packages and .zip to check an integration before any releases?

**Comment by CharliePoole** [comment]
https://www.myget.org/F/nunit/api/v2

**Comment by NikolayPianikov** [comment]
Thank you, but I suppose it does not contain .zip installation.
- How do you think: should we  check a version from master/other branches? 
- Should we add an indicator about build status to github/NUnit? 
- Did we plan to stop building teamcity-event-listener on the common CI or we will continue (to have assembly and NuGet package)? Or JetBrains should provide them?

**Comment by CharliePoole** [comment]
I guess I'm surprised that you can't use the nuget package for the integration test.

If you need a zip package, you have to get it from the appveyor feed, but you should only select builds that have the suffix "-master". https://ci.appveyor.com/nuget/nunit

A build status indicator would be great. You can just do a PR for that.

"Common CI" - I don't know what you mean.

"Jetbrains should provide them" - I thought that the decision in our skype call was that NUnit should continue to hold all this and that you would be a contributor. I was OK with either approach, but our keeping it is the only way to have it included in any future packages.

BTW - I'm figuring that it's OK to drop the teamcity listener from our packages temporarily, up to the time when we do a new release. That only affects the developers - like you and me - and doesn't affect users. So don't be afraid if you see it disappear from the msi temporarily!

**Comment by NikolayPianikov** [comment]
We can use nuget packages, but .zip has another structure of directories and we could test it too. Oh sure, NUnit should continue to hold the TeamCity ext as we've discussed in our skype call.

**Comment by CharliePoole** [comment]
I suggest waiting till the zip structure stabilizes after we split the repositories.

BTW... the myget and appveyor feeds no longer use "-master" as a suffix. You will now want to get packages named like `NUnit-3.5.0-dev-nnnnn`.

**Comment by NikolayPianikov** [comment]
Ok
I am installing last versions of packages to test and they look like NUnit-3.5.0-dev-nnnnn

**Comment by NikolayPianikov** [comment]
About .zip I've added another issue #11
